// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Context;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220823204948_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.RequestUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestUrls");
                });

            modelBuilder.Entity("Domain.Entities.TranslateRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestUrlId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RequestUrlId")
                        .IsUnique();

                    b.ToTable("TranslateRequests");
                });

            modelBuilder.Entity("Domain.Entities.TranslateResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TranslateRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TranslateRequestId")
                        .IsUnique();

                    b.ToTable("TranslateResponses");
                });

            modelBuilder.Entity("Domain.Entities.TranslateRequest", b =>
                {
                    b.HasOne("Domain.Entities.RequestUrl", "RequestUrl")
                        .WithOne("TranslateRequest")
                        .HasForeignKey("Domain.Entities.TranslateRequest", "RequestUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestUrl");
                });

            modelBuilder.Entity("Domain.Entities.TranslateResponse", b =>
                {
                    b.HasOne("Domain.Entities.TranslateRequest", "TranslateRequest")
                        .WithOne("TranslateResponse")
                        .HasForeignKey("Domain.Entities.TranslateResponse", "TranslateRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TranslateRequest");
                });

            modelBuilder.Entity("Domain.Entities.RequestUrl", b =>
                {
                    b.Navigation("TranslateRequest")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.TranslateRequest", b =>
                {
                    b.Navigation("TranslateResponse")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
